---
title: "Lassa fever"
description: |
  This is where I list all of my Lassa work
site: distill::distill_website
date: April 06, 2021
output:
    distill::distill_article:
      toc: true
bibliography: website_refs.bib
categories:
    - Lassa
    - One health
    - Ecology
    - Zoonoses
---

## *Lassa mammarenavirus* assay development

**In progress**

Diagnostics for Lassa mammarenavirus (LASV) are challenging due to the variability in viral sequence and structure. Several commercial PCR and antibody kits are available. To our knowledge there no pan-species antibody assays. To support our ongoing work on understanding the epidemiology and transmission dynamics in multi-species systems in endemic regions we have begun developing a cross-species assay. We adopted an approach that has been found to be successful for *Peste des petits ruminants* a virus that affects goats, sheep and camels and is targeted for eradication. These assays are built on the Luciferase Immunoprecipitation System [@berguido_specific_2016] which detect the presence of antibodies against the presented antigen.

Our work so far in the development of the assay is presented in the following posts:

  - [Identification of potential antigenic epitopes](posts/2021-04-06-luciferase-immunoprecipitations-system/index.html)
  
## Rodent ecology and zoonoses studies in West Africa

**In progress**

I am in the process of conducting a scoping review to consolidate prior research that has involved the trapping of individual rodents in the WHO West Africa region. I have made my initial results available below. I will continue to develop this and produce a data resource to accompany this work.

  - [Associations of environmental and human factors with altered rodent populations in West Africa: A scoping review](posts/scoping-review/index.html)

## Rodent trapping to inform a dynamic rodent assemblage and population model in Eastern Sierra Leone

**In progress**

A pilot study has been performed to inform a planned 2 year programme of repeat trapping in several settings in Sierra Leone. The pilot study is being presented at the [Planetary Health Annual Meeting](https://www.planetaryhealthannualmeeting.com/). For which I am producing a poster and accompanying video that will be linked here when ready. The initial report is available below.

  - [Rodent trapping pilot (November-December 2020)](posts/2021-04-06-rodent-trapping-pilot/index.html)